server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dylanzote/microservices.git
          username: dylanzote
          password: lazovy55667788
          default-label: main
          clone-on-start: true


